#!/usr/bin/env osascript
on run argv
    tell application "Finder" to set iTermExists to exists my POSIX file "/Applications/iTerm.app"

    if iTermExists
        tell application "iTerm"
            activate

            tell the first terminal
                tell the last session
                    write text argv as string
                end tell
            end tell
        end tell
    else
        tell application "Terminal"
            activate
            tell application "System Events" to keystroke "n" using {command down}
            do script argv as string in window 1
        end tell
    end if
end run
